### ISSUE TITLE
Issue since 1.4.3 update

### ISSUE THREAD

**Issue by AndyRes** [aurovrata/cf7-google-map#3]
Hello, thank you for great plugin!

We get the following javascript error in /plugins/cf7-google-map/public/partials/cf7-googlemap.php

Uncaught ReferenceError: address is not defined

it works again when we uncomment line 137:
      var address = $('input#address-<?= $tag->name?>', map_container );
and comment out line 173:
      //var address='';

https://prnt.sc/s93rnh

Hope you can fix that in future release.
Thank you

**Comment by aurovrata** [comment]
which line is the error being reported on?

line 137 has been commented out on prupose and that variable is no longer being used.

**Comment by AndyRes** [comment]
Hope this can help.
https://prnt.sc/s9slke
https://prnt.sc/s9slwi

**Comment by aurovrata** [comment]
Oops. Yes, forgot to update the field...

I just made a fix over my phone....

https://github.com/aurovrata/cf7-google-map/releases/tag/v1.4.5

Can you try it and see if it fixes it

**Comment by AndyRes** [comment]
all seems to be working now, thank you!

**Comment by aurovrata** [comment]
great! thanks for confirming
