### ISSUE TITLE
Edge gives javascript error

### ISSUE THREAD

**Issue by thomashoeky** [aurovrata/cf7-google-map#4]
Hello
I've been using your plugin for a while and it's amazing but unfortunately it gives an error in the Edge browser

`SCRIPT1028: SCRIPT1028: Expected identifier, string or number
cf7-googlemap.js (68,33)`
Which is this part of the script:
` let $map3 = et_map.gmap3({...map_settings, ...cf7GoogleMap.gmap3_settings}).marker({...marker_settings, ...cf7GoogleMap.marker_settings}).on('dragend', fireMarkerUpdate).then(function(result){
        googleMap = this.get(0);
        googleMarker = this.get(1);
      });`

Could you take a look at this? 
Thank you very much

**Comment by aurovrata** [comment]
looks like Edge is not fully ES6 compliant.  Please downgrade to [v1.4.5](https://downloads.wordpress.org/plugin/cf7-google-map.1.4.5.zip)

**Comment by thomashoeky** [comment]
Yup that worked! Thank you.
Will try updating again in a few weeks or so, but atleast I know how to fix it

**Comment by aurovrata** [comment]
v1.5 basically moved the entire js into a separate file rather than being embeded into the html form which was a pain to debug.  The js also was converted to ES6 std.
