### ISSUE TITLE
 Cannot read property 'addListener' of undefined 

### ISSUE THREAD

**Issue by jflaflamme** [aurovrata/cf7-google-map#6]
Hello @aurovrata and thanks for your plugins.

Using the latest WP, I get this error (I haven't used the plugin before, so maybe not related).

`jquery.min.js?ver=3.5.1:2 jQuery.Deferred exception: Cannot read property 'addListener' of undefined TypeError: Cannot read property 'addListener' of undefined
    at s.fn.init.$.fn.initCF7googleMap (https://mysite.com/wp-content/plugins/cf7-google-map/public/js/cf7-googlemap.js?ver=1.7.3:137:17)`

This checked or not doesn't make a difference.
![image](https://user-images.githubusercontent.com/712558/103208546-77fa8a80-4933-11eb-8fc5-f2de73d88b0c.png)

Thanks in advance.

**Comment by aurovrata** [comment]
Thank you for the big report.

This is due to the fact that you are using jQuery 3.

Wordpress uses jQuery 1.12 by default.

I will fix this next week

**Comment by aurovrata** [comment]
this is now fixed in v1.8.  Please git it a try.
