### ISSUE TITLE
Google map on Popup/Modal

### ISSUE THREAD

**Issue by moikzz214** [aurovrata/cf7-google-map#7]
Hi! just wandering if I can reinitialize the function call for map once button is click to show the modal with the map.
As currently it doesn't show on modal but working fine without modal.

**Comment by aurovrata** [comment]
I am assuming you're talking about Boostrap modal....  I have never used Boostrap so I am not sure.

However, I guess I could introduce a custom event listener for the initialisation of the map.  This way once your modal window is opened you can fire the event on the map container to initialise it.

Would his work?

**Comment by moikzz214** [comment]
If i can re-initialize your function from a custom function that would be great.
Your idea is great also. 

Thanks

**Comment by moikzz214** [comment]
Looking forward to it

**Comment by aurovrata** [comment]
This is now implemented in v1.8.  Please read [FAQ](https://wordpress.org/plugins/cf7-google-map/#faq) #12 on the plugin page to see how to get it to work for your modal.

PS:  Do you use the [CF7 Smart Grid extension](https://wordpress.org/plugins/cf7-grid-layout/) for your form?  If so does it work on the modal popup?
